### ISSUE TITLE
minimal addGraph doesnt function

### ISSUE THREAD

**Issue by Seeron** [topfdrummer/setlX#11]
g1 := plot_addGraph(can, "sin(x)");

Error in "g1 := plot_addGraph(can, "sin(x)")":
Error in "plot_addGraph(can, "sin(x)")":
Error in "procedure( canvas ,  functiondefinition ,  graphname , graphcolor := 1,  plotarea  := 1) { /\* predefined procedure `plot_addGraph' */ }(can, "sin(x)")":
'plot_addGraph( canvas ,  functiondefinition ,  graphname , graphcolor := 1,  plotarea  := 1)' is defined with at least 3 instead of 2 parameters.

**Comment by topfdrummer** [comment]
We deleted this minimal addGraph from the Interface because it would be too complicated for user if I overload the PD-Methods in SetlX too much.
If there is the need, i coud add something `plot_addSimpleGraph(canvas, function)` as new Function.

**Comment by Seeron** [comment]
probably not needed. Issue closed
