### ISSUE TITLE
command createCanvas() still works

### ISSUE THREAD

**Issue by Seeron** [topfdrummer/setlX#12]
the command createCanvas() still works. 

plot_createCanvas() should be used

**Comment by topfdrummer** [comment]
can not reproduce with current master 7eb32c9edc69c8227ae725a3e6d6b25b19ba7456

> => c := createCanvas();
> 
> Error in "c := createCanvas()":
> Error in "createCanvas()":
> Left hand side "createCanvas" is undefined.

same as 

> => a:= asdf();
> Error in "a := asdf()":
> Error in "asdf()":
> Left hand side "asdf" is undefined.
