### ISSUE TITLE
Colorlist in addParamGraph doesnt get recognized

### ISSUE THREAD

**Issue by Seeron** [topfdrummer/setlX#24]
trying to create a ParamGraph with a color specified, e.g. g1 := plot_addParamGraph(c, "cos(x)", "sin(x)", "circle", [-3.15, 3.15], [255,0,0]); returns  "Parameter graphcolor have to consots of exact three values(RGB)" even though its correctly defined.

**Comment by topfdrummer** [comment]
Fixed with commit 8e0605b
