### ISSUE TITLE
move state to calc function

### ISSUE THREAD

**Issue by topfdrummer** [topfdrummer/setlX#26]

**Comment by topfdrummer** [comment]
should be fixed with 6c430e47dc5abda22f15c64b9908d103ff7f3fa8

**Comment by topfdrummer** [comment]
class: VariableScope
method: getBinding
row: 364 binding.scopeDepth() is 1, restrictedToFunctionsBeneath is 2

**Comment by Seeron** [comment]
fixed with e7df05be9ea423e2d96364754135be4e28980ea5
