### ISSUE TITLE
Calcfunction incorrect

### ISSUE THREAD

**Issue by Seeron** [topfdrummer/setlX#8]
after using g1 := addGraph(c, "x*_2 -2"); wrong graph is showing. addGraph(c, "x_x -2"); works fine.

(-1)**2 returns -1. Probably paranthesis missing

**Comment by topfdrummer** [comment]
I have testet the Calcfunction but could not see any error. 
Because i use the setlx evaluation it seems to lie there. 
With `-1**2` i get -1 in the setl-interpreter too, whereas `(-1)**2` result in 1, which is correct.

**Comment by Seeron** [comment]
the problem is, that when using a variable, like x *\* 2 you shouldnt need to set paranthesis. In calcfunction, x is just replaced with the number so x *\* 2 gets -2 *\* 2 which results in -4, Its probably better, to replace the variables with (-2) instead of just -2

**Comment by topfdrummer** [comment]
fixed with commit 8e37a27
